### File: Dockerfile.v3
##
## MozJPEG v3を組み立てる。
##
## Usage:
##
## ------ Text ------
## docker buildx build -f Dockerfile.v3
## ------------------
##
## Build arg:
##
##   BUILD_BASE - ビルド時に使用するイメージ名。
##   REV - Gitリポジトリのリビジョン識別子。
##   AUTORECONF_OPTS - autoreconfコマンドへのオプション。
##   CONFIGURE_OPTS - configureコマンドへのオプション。
##   MAKE_OPTS - makeコマンドへのオプション。
##
## Secret id:
##
##   attach - uaコマンド用のアタッチ設定ファイル。
##
## Metadata:
##
##   id - 7f3ae4b7-02fb-45fa-a85c-aef4429eb3aa
##   author - <qq542vev at https://purl.org/meta/me/>
##   version - 1.0.2
##   created - 2025-11-18
##   modified - 2026-01-03
##   copyright - Copyright (C) 2025-2025 qq542vev. All rights reserved.
##   license - <GPL-3.0-only at https://www.gnu.org/licenses/gpl-3.0.txt>
##
## See Also:
##
##   * <Project homepage at https://github.com/qq542vev/build-mozjpeg>
##   * <Bag report at https://github.com/qq542vev/build-mozjpeg/issues>

ARG BUILD_BASE="ubuntu:18.04"
FROM ${BUILD_BASE} AS build

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TZ=UTC0 DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-euo", "posix", "-o", "pipefail", "-c"]

RUN \
	apt-get update && \
	apt-get install -y --no-install-recommends \
		ca-certificates ubuntu-advantage-tools

RUN --mount=type=secret,id=attach \
	ATTACH_FILE=/run/secrets/attach && \
	if [ -s "${ATTACH_FILE}" ]; then \
		ua attach --attach-config "${ATTACH_FILE}" && \
		trap 'ua detach --assume-yes || exit "${?}"' EXIT && \
		apt-get update && \
		apt-get upgrade -y --no-install-recommends; \
	fi && \
	apt-get install -y --no-install-recommends \
		autoconf automake git libpng-dev libtool make nasm pkg-config && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /work/build
COPY .git ..

ARG REV=v3.3.1
RUN git archive --format=tar "${REV}" | tar -xvC ..

ARG AUTORECONF_OPTS=
RUN autoreconf -fiv ${AUTORECONF_OPTS} ..

ARG CONFIGURE_OPTS=
RUN sh ../configure --without-simd ${CONFIGURE_OPTS} 2>&1 | tee configure.log

ARG MAKE_OPTS=
RUN make ${MAKE_OPTS} | tee make.log
RUN mkdir stage && make ${MAKE_OPTS} DESTDIR="${PWD}/stage" install && tar -czvf "mozjpeg-${REV}-Linux-$(uname -m).tar.gz" -C stage .
RUN make ${MAKE_OPTS} deb || :

FROM scratch
COPY --from=build /work/build/mozjpeg*.tar.gz /work/build/mozjpeg*.deb /
COPY --from=build /work/build/configure.log /work/build/make.log /
