### File: Dockerfile.v2
##
## mozjpeg v2を組み立てる。
##
## Usage:
##
## ------ Text ------
## docker buildx build -f Dockerfile.v2
## ------------------
##
## Build arg:
##
##   BUILD_BASE - ビルド時に使用するイメージ名。
##   MOZJPEG_TAG - mozjpegのGitタグまたはコミットID。
##   AUTORECONF_OPTS - autoreconfコマンドへのオプション。
##   CONFIGURE_OPTS - configureコマンドへのオプション。
##   MAKE_OPTS - makeコマンドへのオプション。
##
## Secret id:
##
##   attach - uaコマンド用のアタッチ設定ファイル。
##
## Metadata:
##
##   id - 0ff9d5a0-0512-41ad-a2c5-61b3e4d125c4
##   author - <qq542vev at https://purl.org/meta/me/>
##   version - 1.0.1
##   created - 2025-11-18
##   modified - 2025-12-24
##   copyright - Copyright (C) 2025-2025 qq542vev. All rights reserved.
##   license - <GPL-3.0-only at https://www.gnu.org/licenses/gpl-3.0.txt>
##
## See Also:
##
##   * <Project homepage at https://github.com/qq542vev/build-mozjpeg>
##   * <Bag report at https://github.com/qq542vev/build-mozjpeg/issues>

FROM ubuntu:18.04 AS build

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TZ=UTC0 DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-euo", "posix", "-o", "pipefail", "-c"]

RUN \
	apt-get update && \
	apt-get install -y --no-install-recommends \
		ca-certificates ubuntu-advantage-tools

RUN --mount=type=secret,id=attach \
	ATTACH_FILE=/run/secrets/attach && \
	if [ -s "${ATTACH_FILE}" ]; then \
		ua attach --attach-config "${ATTACH_FILE}" && \
		trap 'ua detach --assume-yes || exit "${?}"' EXIT && \
		apt-get update && \
		apt-get upgrade -y --no-install-recommends; \
	fi && \
	apt-get install -y --no-install-recommends \
		autoconf automake git libpng-dev libtool make nasm pkg-config sudo && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /work/build
COPY .git ..

ARG MOZJPEG_TAG=v2.1
RUN git archive --format=tar "${MOZJPEG_TAG}" | tar -xvC ..

ARG AUTORECONF_OPTS=
RUN autoreconf -fiv ${AUTORECONF_OPTS} ..

ARG CONFIGURE_OPTS=
RUN sh ../configure --without-simd ${CONFIGURE_OPTS} 2>&1 | tee configure.log

ARG MAKE_OPTS=
RUN make ${MAKE_OPTS} 2>&1 | tee make.log
RUN mkdir stage && make ${MAKE_OPTS} DESTDIR="${PWD}/stage" install && tar -czvf "libmozjpeg-${MOZJPEG_TAG}-Linux-$(uname -m).tar.gz" -C stage .
RUN make ${MAKE_OPTS} deb || :

FROM scratch AS final
COPY --from=build /work/build/libmozjpeg*.tar.gz /work/build/libmozjpeg*.deb /
COPY --from=build /work/build/configure.log /work/build/make.log /
